@startuml
start
:Показать меню выбора;
if (Выбрана новая трасса?) then (Да)
  :Загрузить параметры трассы;
  :Генерация аватаров;
  :Загрузка DQN модели;
else (Нет)
  :Использовать сохраненные настройки;
endif
:Инициализация физического движка;
:Создание объектов машин;
while (Гонка активна?) is (Да)
  :Обработка ввода игрока;
  :Получение действий ботов;
  :Расчет физики;
  :Проверка коллизий;
  :Обновление позиций;
  :Рендер кадра;
endwhile (Нет)
:Показать результаты;
stop
@enduml