@startuml
left to right direction
actor Игрок
rectangle Система {
  usecase "Выбрать трассу" as UC0
  usecase "Играть в гонку" as UC1
  usecase "Сгенерировать аватары" as UC2
  usecase "Загрузить модель DQN" as UC3
  usecase "Обучить модель" as UC4
}

Игрок --> UC0
Игрок --> UC4
UC0 .> UC2 : includes
UC0 .> UC3 : includes
UC1 .> UC0 : extends
@enduml